import '../models/word.dart';

class InitialData {
  static final List<Word> words = [
    Word(word: 'achieve', meaning: '달성하다, 성취하다', example: 'We achieved our goal.'),
    Word(word: 'acquire', meaning: '획득하다, 습득하다', example: 'He acquired new skills.'),
    Word(word: 'adequate', meaning: '적절한, 충분한', example: 'We have adequate resources.'),
    Word(word: 'affect', meaning: '영향을 미치다', example: 'This will affect our decision.'),
    Word(word: 'analyze', meaning: '분석하다', example: 'We need to analyze the data.'),
    Word(word: 'approach', meaning: '접근하다, 방법', example: 'Let\'s try a different approach.'),
    Word(word: 'appropriate', meaning: '적절한', example: 'Choose the appropriate method.'),
    Word(word: 'assessment', meaning: '평가, 사정', example: 'The assessment was fair.'),
    Word(word: 'benefit', meaning: '이익, 혜택', example: 'This has many benefits.'),
    Word(word: 'circumstance', meaning: '상황, 환경', example: 'Under these circumstances, we must act.'),
    Word(word: 'colleague', meaning: '동료', example: 'My colleague helped me.'),
    Word(word: 'comprehensive', meaning: '포괄적인', example: 'We need a comprehensive plan.'),
    Word(word: 'concern', meaning: '관심사, 우려', example: 'Safety is our main concern.'),
    Word(word: 'conduct', meaning: '수행하다, 행동', example: 'We will conduct a survey.'),
    Word(word: 'consequence', meaning: '결과', example: 'Consider the consequences.'),
    Word(word: 'considerable', meaning: '상당한', example: 'There was considerable damage.'),
    Word(word: 'consistent', meaning: '일관된', example: 'Be consistent in your approach.'),
    Word(word: 'contribute', meaning: '기여하다', example: 'Everyone should contribute.'),
    Word(word: 'criteria', meaning: '기준', example: 'What are the criteria for selection?'),
    Word(word: 'significant', meaning: '중요한', example: 'This is a significant change.'),
    Word(word: 'demonstrate', meaning: '입증하다, 보여주다', example: 'Let me demonstrate the process.'),
    Word(word: 'derive', meaning: '얻다, 유래하다', example: 'We derive energy from food.'),
    Word(word: 'distribute', meaning: '분배하다', example: 'Distribute the materials evenly.'),
    Word(word: 'effective', meaning: '효과적인', example: 'This is an effective solution.'),
    Word(word: 'eliminate', meaning: '제거하다', example: 'We must eliminate errors.'),
    Word(word: 'emphasize', meaning: '강조하다', example: 'I want to emphasize this point.'),
    Word(word: 'enhance', meaning: '향상시키다', example: 'This will enhance performance.'),
    Word(word: 'ensure', meaning: '보장하다', example: 'Ensure all doors are locked.'),
    Word(word: 'establish', meaning: '설립하다, 확립하다', example: 'We will establish new rules.'),
    Word(word: 'estimate', meaning: '추정하다', example: 'Estimate the total cost.'),
    Word(word: 'evaluate', meaning: '평가하다', example: 'Evaluate each option carefully.'),
    Word(word: 'evident', meaning: '명백한', example: 'The problem is evident.'),
    Word(word: 'facilitate', meaning: '촉진하다', example: 'This will facilitate communication.'),
    Word(word: 'fundamental', meaning: '기본적인', example: 'This is a fundamental principle.'),
    Word(word: 'generate', meaning: '생성하다', example: 'Generate new ideas.'),
    Word(word: 'identify', meaning: '확인하다, 식별하다', example: 'Identify the main issues.'),
    Word(word: 'implement', meaning: '실행하다', example: 'We will implement the plan.'),
    Word(word: 'imply', meaning: '암시하다', example: 'What does this imply?'),
    Word(word: 'indicate', meaning: '나타내다', example: 'The data indicates a trend.'),
    Word(word: 'initial', meaning: '초기의', example: 'The initial response was positive.'),
    Word(word: 'maintain', meaning: '유지하다', example: 'Maintain a positive attitude.'),
    Word(word: 'obtain', meaning: '얻다', example: 'Obtain permission first.'),
    Word(word: 'occur', meaning: '발생하다', example: 'When did this occur?'),
    Word(word: 'participate', meaning: '참여하다', example: 'Everyone should participate.'),
    Word(word: 'perceive', meaning: '인식하다', example: 'How do you perceive this?'),
    Word(word: 'priority', meaning: '우선순위', example: 'Safety is our top priority.'),
    Word(word: 'require', meaning: '필요로 하다', example: 'This task requires attention.'),
    Word(word: 'resolve', meaning: '해결하다', example: 'We need to resolve this issue.'),
    Word(word: 'specific', meaning: '구체적인', example: 'Be more specific.'),
    Word(word: 'strategy', meaning: '전략', example: 'We need a new strategy.'),
  ];
}
